services:
  - type: web
    name: meeting-center
    env: node
    region: sgp
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free # Try to use the free plan if available
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /data
