services:
  - type: web
    name: meeting-center
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

